# Railway configuration for Local Web Insights Canada
# Settings are primarily managed in the Railway UI dashboard
# Using ts-node-dev for deployment to bypass build errors

[build]
builder = "nixpacks" 
# rootDirectory is set in the Railway UI
# buildCommand is set in the Railway UI (should be just 'npm install')

[deploy]
restartPolicyType = "ON_FAILURE"
# rootDirectory is set in the Railway UI
startCommand = "npm run dev" # Use dev command to bypass tsc build
# healthcheckPath is set in the Railway UI

[variables]
NODE_ENV = "development" # Use development mode for ts-node-dev
PORT = "8080"
LOG_LEVEL = "info"
# Other variables like REDIS_URL, SUPABASE_URL etc. should be set 
# in the Railway dashboard (preferably as shared variables) 