# Railway configuration for scraper service

[build]
rootDirectory = "services/scraper"
buildCommand = "npm install"

[deploy]
rootDirectory = "services/scraper"
startCommand = "npm run dev"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production" 