# Railway configuration for Local Web Insights Canada
# Primary configuration for deploying the scraper service

[build]
builder = "NIXPACKS"
buildCommand = "cd services/scraper && npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd services/scraper && npm start"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch the scraper service files
watchPatterns = [
  "services/scraper/**/*"
]

# Service dependencies
[services]
redis = "redis"

[variables]
NODE_ENV = "production"
PORT = "8080"
LOG_LEVEL = "info"
# Set GOOGLE_PLACES_API_KEY to the same value as GOOGLE_MAPS_API_KEYS for compatibility
GOOGLE_PLACES_API_KEY = "${{GOOGLE_MAPS_API_KEYS}}"
