# Minimal Railway configuration for scraper service

[build]
rootDirectory = "services/scraper"

[deploy]
rootDirectory = "services/scraper"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production" 