# Railway configuration for Scraper Service
# Using root directory for monorepo setup

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "node dist/index.js"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
rootDirectory = "services/scraper"

[variables]
NODE_ENV = "development"
PORT = "8080"
LOG_LEVEL = "info" 