# Railway configuration for Local Web Insights Canada
# Settings are primarily managed in the Railway UI dashboard
# Using ts-node-dev for deployment to bypass build errors

[build]
builder = "NIXPACKS"
buildCommand = "cd services/scraper && npm install"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd services/scraper && npm run dev"
healthcheckPath = "/api/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "development" # Use development mode for ts-node-dev
PORT = "8080"
LOG_LEVEL = "info"
# Other variables like REDIS_URL, SUPABASE_URL etc. should be set 
# in the Railway dashboard (preferably as shared variables) 