# Railway configuration for the scraper service only

[build]
builder = "nixpacks"
rootDirectory = "services/scraper"
buildCommand = "npm install"

[deploy]
rootDirectory = "services/scraper"
startCommand = "npm run dev"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "8080" 