# Railway configuration for Scraper Service
# Using workspace scripts for build and deployment

[build]
builder = "NIXPACKS"
buildCommand = "cd services/scraper && npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd services/scraper && npm start"
# Temporarily disable health checks until service startup is fixed
# healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch the scraper service files
watchPatterns = [
  "services/scraper/**/*"
]

# Service dependencies
[services]
redis = "services/redis"

[variables]
NODE_ENV = "production"
PORT = "8080"
LOG_LEVEL = "info"
# Use Railway's internal Redis URL since both services are in the same network
REDIS_URL = "redis://default:KeMbhJaNOKbuIBnJmxXebZGUTsSYtdsE@redis.railway.internal:6379"

# Redis configuration will be automatically injected by Railway
# Remove hardcoded Redis URL and use Railway's service linking
# REDIS_URL will be automatically set by Railway when the Redis service is linked
