# Railway configuration for Scraper Service
# Using service path to point to the correct directory

[build]
builder = "NIXPACKS"
servicePath = "services/scraper"
buildCommand = "npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "node dist/index.js"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "development"
PORT = "8080"
LOG_LEVEL = "info" 