# Railway configuration for Scraper Service
# Using workspace scripts for build and deployment

[build]
builder = "NIXPACKS"
buildCommand = "npm run scraper:build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run scraper:start"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch the scraper service files
watchPatterns = [
  "services/scraper/**/*"
]

[variables]
NODE_ENV = "development"
PORT = "8080"
LOG_LEVEL = "info" 