# Railway configuration for Scraper Service
# Using root directory for monorepo setup

[build]
builder = "NIXPACKS"
buildCommand = "cd services/scraper && npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd services/scraper && node dist/index.js"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch the scraper service files
watchPatterns = [
  "services/scraper/**/*"
]

[variables]
NODE_ENV = "development"
PORT = "8080"
LOG_LEVEL = "info" 