
# Railway configuration for Scraper Service
# Using workspace scripts for build and deployment

[build]
builder = "NIXPACKS"
buildCommand = "cd services/scraper && npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd services/scraper && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch the scraper service files
watchPatterns = [
  "services/scraper/**/*"
]

# Service dependencies - let Railway handle the connection details
[services]
redis = "services/redis"

[variables]
NODE_ENV = "production"
PORT = "8080"
LOG_LEVEL = "info"
# Let Railway automatically inject REDIS_URL when services are linked
# Note: Remove hardcoded Redis URL to avoid conflicts
# REDIS_URL will be automatically set by Railway when the Redis service is linked
