// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './schema.js';

const SUPABASE_URL = "https://sirryoeizmlubsuspmic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcnJ5b2Vpem1sdWJzdXNwbWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTE2NTQsImV4cCI6MjA1OTI4NzY1NH0.RyczdU6NNga0OJ5eWcz5OJlZ9u9IdmdsAycPKJwVokk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
