
version: '3.8'

services:
  scraper:
    platform: linux/amd64
    build: 
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./scraper/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - MADEWITH_API_KEY=${MADEWITH_API_KEY}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_CREDENTIALS=${GCS_CREDENTIALS}
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  analysis:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - ./analysis:/app
      - /app/node_modules
    depends_on:
      - redis
      - scraper

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 
