# Railway configuration for Redis Service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "redis-server --port $PORT --requirepass $REDIS_PASSWORD"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Redis doesn't serve HTTP, so we can't use HTTP health checks
# healthcheckPath = "/"
# healthcheckTimeout = 10

[variables]
PORT = "6379"
REDIS_PASSWORD = "KeMbhJaNOKbuIBnJmxXebZGUTsSYtdsE" 