# Railway configuration for Redis Service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "redis-server --port $PORT --requirepass $REDIS_PASSWORD"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 10

[variables]
PORT = "6379"
REDIS_PASSWORD = "KeMbhJaNOKbuIBnJmxXebZGUTsSYtdsE" 